# Generated by Django 2.1.4 on 2019-01-16 15:07

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='O mnie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=models.IntegerField(blank=True, help_text='To pole przydaje się w przypadku tworzenia wydarzeń, aby użytkownicy w łatwy sposób mogli się z Tobą skontaktować.', null=True, verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='Zdjęcie profilowe'),
        ),
    ]
