# Generated by Django 2.1.4 on 2019-01-04 11:28

from django.db import migrations, models
import taggit_selectize.managers


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181229_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body',
            field=models.TextField(verbose_name='Szczegóły wydarzenia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='button',
            field=models.CharField(blank=True, default='Więcej informacji', help_text='Nazwa przycisku, który przekieruje użytkownika na wybraną przez Ciebie stronę. Na przykład na stronę z zakupem biletu. Więc można dodać w nim na przykład "Kup bilet" lub "Więcej informacji".', max_length=50, null=True, verbose_name='Przycisk'),
        ),
        migrations.AlterField(
            model_name='event',
            name='button_link',
            field=models.URLField(blank=True, help_text='Link przekierowujący użytkownika klikającego w przycisk.', max_length=255, null=True, verbose_name='Przekierowanie przycisku'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(blank=True, help_text='To pole jest dodatkowe, jeśli nie masz dokładnej daty zakończenia wydarzenia, nie musisz tego podawać.', null=True, verbose_name='Koniec wydarzenia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateTimeField(help_text='Aby dodać godzinę wydarzenia, wystarczy po rozwinięciu kalendarza kliknąć ikonę zegara.', verbose_name='Start wydarzenia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='event', verbose_name='Tło wydarzenia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='localization',
            field=models.CharField(max_length=255, verbose_name='Lokalizacja'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=taggit_selectize.managers.TaggableManager(help_text='Warto wybierać tagi, które już są w bazie. Aby to zrobić wystarczy wpisać dowolny tag, jeśli będzie w bazie wyświetli się i będzie można go zaznaczyć.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tagi'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tytuł'),
        ),
    ]
