# Generated by Django 2.1.4 on 2019-01-08 14:37

from django.db import migrations
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190108_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='localization',
            field=places.fields.PlacesField(blank=True, max_length=255, null=True, verbose_name='Lokalizacja'),
        ),
    ]
