# Generated by Django 2.1.4 on 2019-01-19 14:32

from django.db import migrations, models
import django.db.models.deletion
import taggit_selectize.managers
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190116_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='author',
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_author',
            field=models.ForeignKey(blank=True, help_text='Jeśli nie znajdziesz w bazie autora cytatu, po prostu dopisz go w polu "Cytat", a moderacja dodać autora i edytuje pole.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_author', to='books.Author', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Jeśli niema autora w bazie, dodaj jego imię i nazwisko w opisie, a moderacja doda książkę i edytuje pole.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='books.Author', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Wybierz kategorie dla tej książki', null=True, to='books.Genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='book', verbose_name='Grafika okładki'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='To pole może pozostać puste.', max_length=13),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=tinymce.models.HTMLField(verbose_name='Opis książki'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=taggit_selectize.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tagi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='book',
            field=models.ForeignKey(blank=True, help_text='To pole może zostać puste, jeśli nie znasz książki z którego pochodzi cytat lub jeśli cytat to kogoś wypowiedź. Jeśli jednak niema książki w bazie, dopisz jej nazwę w polu cytat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_book_author', to='books.Book', verbose_name='Książką'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(verbose_name='Cytat'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=taggit_selectize.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tagi'),
        ),
    ]
