# Generated by Django 2.1.4 on 2019-01-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190119_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='quote_author',
            new_name='author',
        ),
    ]
